Repository SrijanShovit/Hostelite-Android, pull requests merged in 2022-10, with the labels that each got.

#5 Report Issue UI
  app/src/main/java/com/example/hostelite/MainActivity.kt
  app/src/main/java/com/example/hostelite/shared/widgets/widgets.kt
  app/src/main/java/com/example/hostelite/student_screens/report_issue.kt
Labels: hacktoberfest-accepted

#10 Add MarkExit Student Screen
  app/src/main/java/com/example/hostelite/MainActivity.kt
  app/src/main/java/com/example/hostelite/student_screens/MarkExit.kt
  app/src/main/java/com/example/hostelite/student_screens/StudentHome.kt
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#16 Alerts screen
  app/src/main/java/com/example/hostelite/MainActivity.kt
  app/src/main/java/com/example/hostelite/admin_screens/AdminAlertsScreen.kt
  app/src/main/java/com/example/hostelite/shared/widgets/widgets.kt
  app/src/main/java/com/example/hostelite/student_screens/Alerts.kt
  app/src/main/java/com/example/hostelite/student_screens/StudentHome.kt
  app/src/main/res/drawable/dp1.png
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#17 updated reame
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#18 Add Complaints Screen for both Student and Admin
  app/src/main/java/com/example/hostelite/MainActivity.kt
  app/src/main/java/com/example/hostelite/admin_screens/AdminHomeScreen.kt
  app/src/main/java/com/example/hostelite/admin_screens/ComplaintScreen.kt
  app/src/main/java/com/example/hostelite/student_screens/MyComplaints.kt
  app/src/main/res/drawable/badfood.png
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#21 admin profile and student profile done
  app/src/main/java/com/example/hostelite/admin_screens/AdminEditProfile.kt
  app/src/main/java/com/example/hostelite/admin_screens/AdminProfileScreen.kt
Labels: hacktoberfest, hacktoberfest-accepted

#24 22 create exit entry screen UI for admin
  README.md
  app/src/main/java/com/example/hostelite/admin_screens/EntryExitReports.kt
Labels: hacktoberfest, hacktoberfest-accepted

#26 student exit entry added
  app/src/main/java/com/example/hostelite/student_screens/MyEntryExitRecords.kt
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#29 Add more screenshots of the app
  Screenshots/Alerts_Student.jpeg
  Screenshots/alerts_admin2.jpeg
  Screenshots/alerts_admin_1.jpeg
  Screenshots/create_account_student.jpeg
  Screenshots/view_complaints_pending.jpeg
  Screenshots/view_complaints_rejected.jpeg
  Screenshots/view_complaints_sorted.jpeg
  Screenshots/view_my_complaints.jpeg
  Screenshots/view_my_complaints2.jpeg
Labels: documentation, hacktoberfest, hacktoberfest-accepted
